config/routes.rb
Rails.application.routes.draw do

  root 'books#index'
  resources :books
  devise_for :users
  resources :authors
  resources :reviews
  resources :charges

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      elsif user.email.nil?
        can :read, :all
      elsif user.moderator?
        can :read, :all
        can :delete, Review
      else
        can [:read,:create], Book
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, :dependent => :delete_all
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :reviews, :dependent => :delete_all
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
  end

  def show
    @author = Author.find(params[:id])
  end

  def delete
    @author = Author.find(params[:id])
    @author.books.map(&:destroy)
    @author.destroy

    redirect_to root_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource :only => [:new, :create]
  def index
    @books = Book.includes(:author).all
  end

  def show
    @book = Book.find(params[:id])
    @review = Review.new
  end

  def new
    unless current_user.nil?
      @book = Book.new
    end
  end

  def create
    @author_exists = Author.all.find_by(name: params[:author])
    @author = @author_exists.nil? ? Author.create(name: params[:book][:author]) : @author_exists
    # binding.pry

    @book = Book.new(book_params)
    @book.author_id = @author.id
    @book.save

    # New Book was created. Now send email alerting me. 
    @user = current_user
    BookMailer.with(user: @user).new_book_email.deliver_now
    redirect_to root_path
  end
  
  def edit
    @book = Book.find(params[:id])
    # binding.pry
  end

  def update
    @book = Book.find(params[:id])
    @author = Author.all.find_by(name: params[:name])
    @book.update(book_params)
    @book.author_id =  @author.id
    @book.save
    redirect_to root_path
  end
  
  def destroy
    @book = Book.find(params[:id])
    # binding.pry
    @book.destroy
    redirect_to root_path
  end
  private
    def book_params
      params.require(:book).permit(:title, :description)
    end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end
  
  def create
    # Amount in cents
    @amount = 500
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
    @book = Book.find(params[:book_id])
    @review = @book.reviews.create(review_params)

    @review.save
    redirect_to book_path(@book)
    # binding.pry
  end

  def delete
    @review = Review.find(params[:id])
    @book = @review.book
    @review.destroy
    redirect_to book_path(@book)
  end

  private
    def review_params
      params.require(:review).permit(:title, :review)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/authors/index.html.erb
<h1>Authors#index</h1>
<p>Find me in app/views/authors/index.html.erb</p>

app/views/authors/show.html.erb
<div class="show-page">
  <h6>books by</h6>
  <h1><%= @author.name %></h1>
  <hr>
  <% @author.books.each do |book| %>
    <p><%= link_to "#{book.title}", book %></p>
  <% end %>
  <% if can? :delete, :all  %>
    <%= link_to "Delete Author", delete_author_path(@author), method: :delete %>
  <% end %>
</div>

app/views/books/_form.html.erb
<label>Book title:</label><br>
<%= text_field_tag :title, @book.title %><br>

<label>Author</label><br>
<%= text_area_tag :author_id, "" %><br>

<label>Book description</label><br>
<%= text_area_tag :description, "" %><br>

<%= submit_tag "Submit Post", class: "btn btn-dark submit" %>

app/views/books/edit.html.erb
<%= form_for @book, url: update_book_path(@book), html: {class: "edit-form"},:action => "update" do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= select_tag "name", options_for_select(Author.all.collect{ |u| [u.name] }) %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit 'Update book', class: 'btn btn-primary' %>
<% end %>

app/views/books/index.html.erb
<div class="index-page">
  <div class="bookshelf">
    <% @books.each do |book| %>
    <div class="book-card bg-light">
      <div class="book-description">
        <h4> <%= book.title %></h4>
        <h5>by <%= book.author.name %></h5>
        <p> Genre: <%= book.description %></p>
        <p> Rating: <%= book.rating %></p>
      </div>
      <div class="index-page-nav-links">
        <button><%= link_to "show", book %></button>
        <% if can? :delete, book %>
        <button><%= link_to "delete", book_path(book.id), method: :delete %></button>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<% if user_signed_in? %>
  <%= form_for @book, url: books_path ,html: {class: "edit-form"}, :action => "create" do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :author %>
    <%= select_tag "name", options_for_select(Author.all.collect{ |u| [u.name] }) %>

    <%= f.label :description, 'Genre' %>
    <%= f.text_field :description %>

    <%= f.submit 'Create book', class: 'btn btn-primary' %>
  <% end %>
<% else %>
  <h1 class= "edit-form">Please sign in </h1>
<% end %>

app/views/books/show.html.erb
<div class="show-page">
  <h2><%= @book.title %></h2>
  <hr>
  <p>Author: <%=link_to  @book.author.name.upcase, author_path(@book.author) %></p>
  <p>Genre: <%= @book.description %></p>
  <%= render "layouts/shared/stripe_form" %>
  <% if can? :update, @book %>
    <%= link_to "edit", edit_book_path(@book.id) %> |
    <%= link_to "delete", book_path(@book.id), method: :delete %>
  <% end %>
  <hr>
  <% unless @book.reviews.nil? %>
    <h4>Reviews</h4>
    <% @book.reviews.each do | review |%>
      <h5>Title: <%= review.title%> </h5>
      <h6>Posted on: <%= review.created_at.strftime("%Y-%m-%d") %></h6>
      <p><%= review.review %></p>
      <% if can? :delete, review %>
          <button><%= link_to "delete", book_path(@book.id), method: :delete %></button>
      <% end %>
      <hr>
    <% end %>
  <% end %>
  <% if user_signed_in? %>
    <h4>Leave a review!</h4>
    <%= form_for(@review, url: new_review_path) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :review %>
      <%= f.text_field :review %>
      <%= hidden_field_tag(:book_id, @book.id) %>
      <%= f.submit 'Submit', class: 'btn btn-primary'%>
    <% end %>
  <% else %>
    <h4>Please sign in to leave a review</h4>
    <%= link_to 'Log In', new_user_session_path %> |
    <%= link_to 'Sign Up', new_user_registration_path %>
  <% end %>
  </div>
</div>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails01</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <h1> Books </h1>
    <li><%= link_to "Home", books_path %><li>
    <% if user_signed_in? %>
        <li>
          <ul>
            <% if can? :create, Book %>
              <li><%= link_to "Add a new book", new_book_path %><li>
            <% end %>

            <li><%= link_to 'Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
          </ul>
          <li><%= current_user.email  %>, you are currently signed in</li>
        </li>
      <% else %>
        <li><%= link_to 'Log In', new_user_session_path %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <% end %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_stripe_form.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Purchase Book"
          data-amount="500"
          data-locale="auto"></script>
<% end %>